# Generated by Django 3.0.3 on 2020-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200216_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updatedatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
